drawing2 = {"message": "", 'auth': ['client'],
                           'actions': [{'type': 'Point', 'timestamp': 1571747340.659661,
                                        'params': {'coord': [406, 185], 'point_color': [0, 0, 255],
                                                   'font_size': 12}, 'client': 'client'},
                                       {'type': 'Point', 'timestamp': 1571747346.41509,
                                        'params': {'coord': [227, 176], 'point_color': [0, 255, 0],
                                                   'font_size': 12}, 'client': 'client'},
                                       {'type': 'Text_box', 'timestamp': 1571747376.62156, 'id': "208_438",
                                        'params': {'x': 208, 'y': 438, 'w': 160, 'h': 32, 'box_color': [30, 30, 30],
                                                   'font': 'timesnewroman', 'font_size': 20,
                                                   'text': 'I am Mr Potato! <3', 'text_color': [0, 0, 0]},
                                        'client': 'client',
                                        'owner': 'client'}]}
